name: brainiak-tutorials
dependencies:
  - python=3.6
  - pip=9.0.3
  - pip:
    - brainiak==0.9.1
    - deepdish==0.3.6
    - ipython==7.7.0
    - matplotlib==3.1.1
    - networkx==2.3
    - nilearn==0.5.2
    - notebook==6.0.1
    - nxviz==0.6.1
    - pandas==0.25.1
    - seaborn==0.9.0
    - watchdog==0.9.0
